# Proxy配置文件
proxy.listenPort=10913
proxy.host=127.0.0.1
proxy.namesrvAddr=127.0.0.1:9876
proxy.storageAdapterType=rocketmq
proxy.brokerAddr=127.0.0.1:10911
proxy.connectTimeoutMillis=3000
proxy.registerProxyToNameServer=false
proxy.proxyBrokerName=ProxyBroker
proxy.proxyClusterName=ProxyCluster
proxy.bossThreadNums=1
proxy.workerThreadNums=4
proxy.routeCacheExpireMillis=30000