proxy.listenPort=10913
proxy.host=127.0.0.1
proxy.namesrvAddr=127.0.0.1:9876
proxy.connectTimeoutMillis=3000
proxy.bossThreadNums=1
proxy.workerThreadNums=8
proxy.routeCacheExpireMillis=30000

proxy.tlsEnabled=false
# proxy.tlsCertPath=/path/to/server.crt
# proxy.tlsKeyPath=/path/to/server.key
# proxy.tlsTrustCertPath=/path/to/ca.crt
proxy.tlsClientAuth=false
